config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources	:projects do
		get 'current_month_generations', :on => :member
		get 'day_generations', :on => :member
		get 'get_ranged_generations_outages', :on => :member
		resources	:machines do
			get 'current_month_generations', :on => :member
			get 'get_ranged_generations_outages', :on => :member
			get 'get_day_list_outages', :on => :member
			resources	:outages				
			resources	:generations
			resources	:machine_statuses
		end
  end
 end

app/models/project.rb
class Project < ApplicationRecord
	has_many	:machines
	
	validates	:name, presence: true
	validates	:location_text, presence: true
	validates	:total_installed_capacity, presence: true
	
	# attr_reader
	def current_month_auxillary
	  self[:current_month_auxillary]
	end
	
	def current_month_auxillary
		self.machines.joins(:generations).where("to_char(generations.generation_date,'YYYYMM')=?",Time.now.strftime("%Y%m")).sum('generations.aux_units_generated')
	end
	
	def current_month_generation
	  self[:current_month_generation]
	end
	
	def current_month_generations
	  self[:current_month_generations]
	end
	
	def current_month_generation
		self.machines.joins(:generations).where("to_char(generations.generation_date,'YYYYMM')=?",Time.now.strftime("%Y%m")).sum('generations.units_generated')
	end
	
	def current_month_generations
		self.machines.joins(:generations).where("to_char(generations.generation_date,'YYYYMM')=?",Time.now.strftime("%Y%m")).group('generations.generation_date').select(["sum(generations.units_generated) as total_units_generated","generations.generation_date","sum(generations.aux_units_generated) as total_auxillary_units","sum(generations.hours_outage) as total_hours_outage"])
	end
	
	# attr_reader
	def current_month_outages
	  self[:current_month_outages]
	end
	
	def current_month_outages
		self.machines.joins(:outages).where("to_char(outages.outage_dt,'YYYYMM')=?",Time.now.strftime("%Y%m")).sum('outages.outage_total_hours')
	end
	
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action	:is_admin?, only: [:new, :create]
	
	def new
		@project = Project.new
	end
	
	
	def create
		@project = Project.new(project_params)
		
		@project.save
		redirect_to @project
	end
	def show
		@project = Project.find(params[:id])
		@machines = @project.machines.all
	end
	
	def index
		@projects = Project.all.sort_by &:name
	end
	
	def current_month_generations
		@project = Project.find(params[:id])
		@project_current_month_generations = @project.current_month_generations
		@total_project_current_month_generation = @project_current_month_generations.sum(&:total_units_generated)
		@total_project_current_month_outage = @project_current_month_generations.sum(&:total_hours_outage)
		@total_project_current_month_aux_units = @project_current_month_generations.sum(&:total_auxillary_units)
		@total_project_current_month_net_generation = @total_project_current_month_generation - @total_project_current_month_aux_units
	
	end
	
	def day_generations
		@project = Project.find(params[:id])
		@search_date = params[:search_date]
		@project_day_generations = @project.machines.joins(:generations).where("to_char(generations.generation_date,'ddMMYYYY')=?",@search_date).select(["machines.name","generations.units_generated","generations.hours_outage"]).order("machines.id asc")
		@total_project_day_generation = @project_day_generations.sum(&:units_generated)
		@total_project_day_outage = @project_day_generations.sum(&:hours_outage)
	end
	
	def get_ranged_generations_outages
		@from_date = params['search_form'][:from_date]
		@to_date = params['search_form'][:to_date]
		@project = Project.find(params[:id])
		@project_day_generations=@project.machines.joins(:generations).where("generations.generation_date between ? and ?",Date.parse(@from_date),Date.parse(@to_date)).select(["generations.generation_date","generations.units_generated"]).group(:generation_date).sum(:units_generated)
		@project_day_aux_generations=@project.machines.joins(:generations).where("generations.generation_date between ? and ?",Date.parse(@from_date),Date.parse(@to_date)).select(["generations.generation_date","generations.aux_units_generated"]).group(:generation_date).sum(:aux_units_generated)
		@project_day_outages=@project.machines.joins(:outages).where("outages.outage_dt between ? and ?",Date.parse(@from_date),Date.parse(@to_date)).select(["generations.generation_date","generations.units_generated"]).group(:outage_dt).sum(:outage_total_hours)
		@date_range = Date.parse(@from_date)..Date.parse(@to_date)
		

	end

	
	private
    def project_params
		params.require(:project).permit(:name, :num_engines, :total_installed_capacity, :location_text, :configuration, :current_month_generation,:current_month_outages)
	end
	
  def is_admin?
	unless current_user.is_admin?
		flash[:alert]="You don't have authorization to add a new project. Please contact Administrator."
		redirect_to projects_path
	end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/current_month_generations.html.erb
<h1>Current Month Daily Generation <%= @project.name %></h1>
<table class='responstable'>
	<thead>
			<tr>
				<th>Generation Date</th>
				<th>Gross Units Generated (LUs)</th>
				<th>Auxillary Units (LUs)</th>
				<th>Net Units Generated (LUs)</th>
				<th>Outage (Hours)</th>
					
			</tr>
		</thead>
	<% @project_current_month_generations.each do |day_generation| %>
		<tbody>
			<tr>
			   <td><%= day_generation.generation_date.strftime('%d/%m/%Y') %></td>
			  <td><%= day_generation.total_units_generated %></td>
			  <td><%= day_generation.total_auxillary_units %></td>
			  <td><%= day_generation.total_units_generated - day_generation.total_auxillary_units %></td>
			  <td><%= day_generation.total_hours_outage %></td>
			</tr>
		
	<% end %>
	<tr>
			  <td>TOTAL:</td>
			  <td><%= @total_project_current_month_generation %></td>
			  <td><%= @total_project_current_month_aux_units %></td>
			  <td><%= @total_project_current_month_net_generation %></td>
			  <td><%= @total_project_current_month_outage %></td>
	</tr>
	<tbody>
</table>
<p><%= link_to 'All Projects', projects_path %></p>

app/views/projects/day_generations.html.erb
<h1>Daily Generation <%= @project.name %> for <%= Date.strptime(@search_date, '%d%m%Y').strftime("%d/%m/%Y") %></h1>
<table class='responstable'>
	<thead>
			<tr>
				<th>Machine</th>
				<th>Units Generated (LUs)</th>
				<th>Outage (Hours)</th>
					
			</tr>
		</thead>
	<% @project_day_generations.each do |day_generation| %>
		<tbody>
			<tr>
			   <td><%= day_generation.name %></td>
			  <td><%= day_generation.units_generated %></td>
			  <td><%= day_generation.hours_outage %></td>
			</tr>
		
	<% end %>
	<tr>
			  <td>TOTAL:</td>
			  <td><%= @total_project_day_generation %></td>
			   <td><%= @total_project_day_outage %></td>
	</tr>
	<tbody>
</table>
<p><%= link_to 'Back to Project', project_path(@project) %></p>
<p><%= link_to 'All Projects', projects_path %></p>

app/views/projects/get_ranged_generations_outages.html.erb
<h1>Data Search Results | <%= @project.name %></h1>
<h4>From: <%= Date.parse(@from_date).strftime("%d-%b-%Y") %> <br/>To: <%= Date.parse(@to_date).strftime("%d-%b-%Y") %></h4>
<hr/>
<table class='responstable'>
	<thead>
			<tr>
				<th>Date</th>
				<th>Gross Units Generated (LUs)</th>
				<th>Aux Units Generated (LUs)</th>
				<th>Net Units Generated (LUs)</th>
				<th>Outage (Hours)</th>
					
			</tr>
		</thead>
	<% @date_range.each do |c_date| %>
		<tbody>
			<tr>
				<td><%= c_date.strftime("%d-%b-%Y") %></td>
				<td><% if @project_day_generations.key?(c_date) %>
						<%= @project_day_generations[c_date] %>
						<% net_generation = @project_day_generations[c_date] %>
					<% end %>
				</td>
				<td><% if @project_day_aux_generations.key?(c_date) %>
						<%= @project_day_aux_generations[c_date] %>
						<% net_generation = net_generation - @project_day_aux_generations[c_date] %>
					<% end %>
				</td>
				<td>	
					<% if net_generation %>
					<%= net_generation %>
					<% end %>
				</td>
				<td>
					<% if @project_day_outages.key?(c_date) %>
						<%= @project_day_outages[c_date] %>
					<% end %>
				</td>
			</tr>
		
	<% end %>
	<tr>
	</tr>
	<tbody>
</table>
<p><%= link_to 'All Projects', projects_path %></p>

app/views/projects/index.html.erb
<h1>Home | Projects</h1>
 
<table class="responsive-table">
  <thead>
  <tr>
    <th>Project</th>
    <th>Location</th>
	<th>Total Installed Capacity (MW)</th>
	<th>Configuration</th>
	<th>Current Month Gross Generation (LUs) </th>
	<th>Current Month Auxillary (LUs)</th>
	<th>Current Month Net Generation (LUs)</th>
	<th>Current Month Outage (Total Hours)</th>
	<th>Link</th>
  </tr>
 </thead>
  <tbody>
  <% @projects.each do |project| %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.location_text %></td>
	  <td><%= project.total_installed_capacity %></td>
	  <td><%= project.configuration %></td>
	  <td><%= project.current_month_generation %></td>
	  <td><%= project.current_month_auxillary %></td>
	  <td><%= project.current_month_generation - project.current_month_auxillary %></td>
	  <td><%= project.current_month_outages %></td>
	  <td><%= link_to 'Show', project_path(project) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<p><%= link_to 'Add New Project', new_project_path %></p>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= form_for @project do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label 'No of Engines' %><br>
    <%= form.text_field :num_engines %>
  </p>
  
  <p>
    <%= form.label :total_installed_capacity %><br>
    <%= form.text_field :total_installed_capacity %>
  </p>
	
  <p>
    <%= form.label 'Location' %><br>
    <%= form.text_field :location_text %>
  </p>
  
  <p>
    <%= form.label :configuration %><br>
    <%= form.text_field :configuration %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/projects/show.html.erb
<h1>Project Details | <%= @project.name %> </h1>
<div class='project_info'>
 
<p>
  <strong>Location:</strong>
  <%= @project.location_text %>
</p>

<p>
  <strong>Total Installed Capacity:</strong>
  <%= @project.total_installed_capacity %>
</p>

<p>
  <strong>Configuration:</strong>
  <%= @project.configuration %>
</p>
</div>
<%= form_for :search_form, url: get_ranged_generations_outages_project_path(@project), method: :get do |form| %>
<table class='responstable'>
	<thead>
		<tr>
			<th colspan=3>Search for data</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<%= form.label :from_date, "Beginning date:" %>
				<%= form.text_field :from_date, :id=> 'from_date' %>
			</td>
			<td>
				<%= form.label :from_date, "End date:" %>
				<%= form.text_field :to_date, :id=> 'to_date' %>
			</td>
			<td><%= form.submit "Search" %></td>
		</tr>
	</tbody>
</table>
<% end %>


<table class='responstable'>
<thead>
		<tr>
			<th>Machine</th>
			<th>Capacity</th>
			<th>Type</th>
			<th>Status</th>
			<th colspan=3>Actions</th>
		</tr>
	</thead>
<% @machines.each do |project_machine| %>
	<tbody>
		<tr>
		   <td><%= link_to project_machine.name,  project_machine_path(@project, project_machine) %></td>
		  <td><%= project_machine.generator_capacity %></td>
		  <td><%= project_machine.generator_type %></td>
		  <td>
			<% if project_machine.machine_status == 'Operational' %>
				<%= image_tag "/assets/green_status_small.png" %>
			<% elsif project_machine.machine_status == 'Shutdown'  %>
				<%= image_tag "/assets/red_status_small.png" %>
			<% else %>
				<%= image_tag "/assets/unknown_status_small.png" %>
			<% end %>
	
			<%= project_machine.machine_status %><br/><%= link_to '(Edit)', new_project_machine_machine_status_path(@project,project_machine), class: 'classic_url' %>
		  </td>
		  <td><%= link_to 'Add Daily Generation', new_project_machine_generation_path(@project,project_machine) %></p>
		  <td><%= link_to 'Add Outage', new_project_machine_outage_path(@project,project_machine) %></p>
		  <td><%= link_to 'Current Month Generation', current_month_generations_project_machine_path(@project,project_machine) %></p>
		</tr>
	<tbody>
<% end %>
</table>
<div class='bottom_links'>
<ul>
<li><%= link_to 'Add Machine', new_project_machine_path(@project) %></li>
<li><%= link_to 'Go to Projects', projects_path %></li>
<ul>
</div>