config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  
  devise_scope :user do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources	:projects do
		get 'current_month_generations', :on => :member
		get 'day_generations', :on => :member
		get 'get_ranged_generations_outages', :on => :member
		resources	:machines do
			get 'current_month_generations', :on => :member
			get 'get_ranged_generations_outages', :on => :member
			get 'get_day_list_outages', :on => :member
			resources	:outages				
			resources	:generations
			resources	:machine_statuses
		end
  end
 end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :project
  has_many	:generations
  has_many	:outages
  has_many	:machine_statuses
  validates	:generator_capacity, presence: true
  
  
  def current_month_generations
	  self[:current_month_generations]
  end
	
  def current_month_generations
		self.generations.joins("LEFT JOIN outages on outages.outage_dt = generations.generation_date and generations.machine_id = outages.machine_id").where("to_char(generations.generation_date,'YYYYMM')=?",Time.now.strftime("%Y%m")).select("generations.id, generations.generation_date,generations.units_generated,generations.aux_units_generated,generations.comment,sum(outages.outage_total_hours) as hours_outage").order("generation_date desc").group("generations.id,generations.generation_date,generations.units_generated,generations.aux_units_generated,generations.comment")
  end
  
   def current_month_outages
	  self[:current_month_outages]
  end
  
  def current_month_outages
		self.outages.where("to_char(outages.outage_dt,'YYYYMM')=?",Time.now.strftime("%Y%m")).select('outages.outage_dt, sum(outages.outage_total_hours) as outage_total_hours').group('outages.outage_dt').order("outage_dt desc")
  end
  
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
   before_action	:is_admin?, only: [:new, :create]

  
  def new
		@project = Project.find(params[:project_id])
		@machine = @project.machines.build
  end

  def create
	  @project = Project.find(params[:project_id])
	  @machine = @project.machines.new(machine_params)
	  @machine.save
	  redirect_to @project
		
  end
  def show
	@project = Project.find(params[:project_id])
	@machine=@project.machines.find(params[:id])
  end

  def edit
  end

  def index
  end
  
  def current_month_generations
	@project = Project.find(params[:project_id])
	@machine = @project.machines.find(params[:id])
	@machine_current_month_generations = @machine.current_month_generations
	@total_machine_current_month_generation = @machine_current_month_generations.sum(&:units_generated)
	#@total_machine_current_month_outage = @machine_current_month_generations.sum(&:hours_outage)
	@total_machine_current_month_outage = @machine.current_month_outages.sum(&:outage_total_hours)
	@total_machine_current_month_aux_units = @machine_current_month_generations.sum(&:aux_units_generated)
	@total_machine_current_month_net_generation = @total_machine_current_month_generation - @total_machine_current_month_aux_units
	
  end

  def get_ranged_generations_outages
		@from_date = params['search_form'][:from_date]
		@to_date = params['search_form'][:to_date]
		@project = Project.find(params[:project_id])
		@machine = @project.machines.find(params[:id])
		@machine_day_generations=@machine.generations.where("generations.generation_date between ? and ?",Date.parse(@from_date),Date.parse(@to_date)).select(["generations.generation_date","generations.units_generated"]).group(:generation_date).sum(:units_generated)
		@machine_day_aux_generations=@machine.generations.where("generations.generation_date between ? and ?",Date.parse(@from_date),Date.parse(@to_date)).select(["generations.generation_date","generations.aux_units_generated"]).group(:generation_date).sum(:aux_units_generated)
		@machine_day_outages=@machine.outages.where("outages.outage_dt between ? and ?",Date.parse(@from_date),Date.parse(@to_date)).select(["generations.generation_date","generations.units_generated"]).group(:outage_dt).sum(:outage_total_hours)
		@date_range = Date.parse(@from_date)..Date.parse(@to_date)
		

	end
	def get_day_list_outages
		@project=Project.find(params[:project_id])
		@machine=@project.machines.find(params[:id])
		@day_date=params[:day]
		@outages = @machine.outages.where("outages.outage_dt = ?", Date.parse(@day_date))
	
	end
  
  private
  def machine_params
      params.require(:machine).permit(:generator_capacity, :generator_type, :name)
  end
  def is_admin?
	unless current_user.is_admin?
		flash[:alert]="You don't have authorization to add machine to this project. Please contact Administrator."
		redirect_to projects_path
	end
  end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/create.html.erb
<h1>Machines#create</h1>
<p>Find me in app/views/machines/create.html.erb</p>

app/views/machines/current_month_generations.html.erb
<h1>Current Month Daily Generation <%= @project.name %></h1>
<p>This month generation: <%= @machine.name %></p>
<table class='responstable'>
	<thead>
			<tr>
				<th>Generation Date</th>
				<th>Gross Units Generated (LUs)</th>
				<th>Auxillary Units (LUs)</th>
				<th>Net Units Generated (LUs)</th>
				<th>Outage (Hours)</th>
				<th>Comments</th>
				<th>Actions</th>
			</tr>
		</thead>
	<% @machine_current_month_generations.each do |day_machine_generation| %>
		<tbody>
			<tr>
			   <td><%= day_machine_generation.generation_date.strftime('%d/%m/%Y') %></td>
			  <td><%= day_machine_generation.units_generated %></td>
			  <td><%= day_machine_generation.aux_units_generated %></td>
			  <td><%= day_machine_generation.units_generated - day_machine_generation.aux_units_generated %></td>
			  <td><%= day_machine_generation.hours_outage %></td>
			  <td><%= day_machine_generation.comment %></td>
			  <td><%= link_to 'Edit',[:edit, @project, @machine, day_machine_generation] %></td>
			</tr>
		
	<% end %>
	<tr>
			  <td>TOTAL</td>
			  <td><%= @total_machine_current_month_generation %></td>
			  <td><%= @total_machine_current_month_aux_units %></td>
			  <td><%= @total_machine_current_month_net_generation %></td>
			  <td><%= @total_machine_current_month_outage %></td>
			  <td></td>
	</tr>
	<tbody>
</table>
<p><%= link_to 'Back to Project', project_path(@project) %></p>
<p><%= link_to 'All Projects', projects_path %></p>

app/views/machines/edit.html.erb
<h1>Machines#edit</h1>
<p>Find me in app/views/machines/edit.html.erb</p>

app/views/machines/get_day_list_outages.html.erb
<h1>Outages List For The Day</h1>
<h2>Project: | <%= @project.name %> </h2>
<h3>Machine: | <%= @machine.name %> </h2>
<div class='project_info'>

<table class='responstable'>
<thead>
		<tr>
			<th>Day</th>
			<th>Outage Id</th>
			<th>Type</th>
			<th>Outage Reason</th>
			<th>Outage Start</th>
			<th>Outage End</th>
			<th>Outage Hours</th>
			<th>Outage Remarks</th>
			<th colspan='1'>Actions</th>
		</tr>
	</thead>
<% @outages.each do |outage| %>
	<tbody>
		<tr>
		   <td><%= outage.outage_dt.strftime("%d-%b-%Y") %></td>
		  <td><%= outage.id %></td>
		  <td><%= outage.outage_type %></td>
		  <td><%= outage.outage_reason %></td>
		  <td><%= outage.outage_start_dt.strftime("%d-%b-%Y %T") %></td>
		  <td><%= outage.outage_end_dt.strftime("%d-%b-%Y %T") %></td>
		  <td><%= outage.outage_total_hours %></td>
		  <td><%= outage.outage_comment%></td>
		  <td><%= button_to 'Delete Outage', project_machine_outage_path(@project, @machine, outage), method: :delete,  data: { confirm: 'Are you sure?' } %></p>
		  
		</tr>
	<tbody>
<% end %>
</table>
<div class='bottom_links'>
<ul>
<li><%= link_to 'Add Machine', new_project_machine_path(@project) %></li>
<li><%= link_to 'Go to Projects', projects_path %></li>
<ul>
</div>

app/views/machines/get_ranged_generations_outages.html.erb
<h1>Search Results | <%= @project.name %> |  <%= @machine.name %> </h1>
<h4>From: <%= Date.parse(@from_date).strftime("%d-%b-%Y") %> <br/>To: <%= Date.parse(@to_date).strftime("%d-%b-%Y") %></h4>
<hr/>
<table class='responstable'>
	<thead>
			<tr>
				<th>Date</th>
				<th>Gross Units Generated (LUs)</th>
				<th>Aux Units Generated (LUs)</th>
				<th>Net Units Generated (LUs)</th>
				<th>Total Outage (Hours)</th>
				<th>List Outages</th>
					
			</tr>
		</thead>
	<% @date_range.each do |c_date| %>
		<tbody>
			<tr>
				<td><%= c_date.strftime("%d-%b-%Y") %></td>
				<td><% if @machine_day_generations.key?(c_date) %>
						<%= @machine_day_generations[c_date] %>
						<% net_generation = @machine_day_generations[c_date] %>
					<% end %>
				</td>
				<td><% if @machine_day_aux_generations.key?(c_date) %>
						<%= @machine_day_aux_generations[c_date] %>
						<% net_generation = net_generation - @machine_day_aux_generations[c_date] %>
					<% end %>
				</td>
				<td>	
					<% if net_generation %>
					<%= net_generation %>
					<% end %>
				</td>
				<td>
					<% if @machine_day_outages.key?(c_date) %>
						<%= @machine_day_outages[c_date] %>
					<% end %>
				</td>
				<td>
					<%= link_to 'Click', get_day_list_outages_project_machine_path(@project,@machine,:day =>c_date) %>
				</td>
			</tr>
		
	<% end %>
	<tr>
	</tr>
	<tbody>
</table>
<p><%= link_to 'All Projects', projects_path %></p>

app/views/machines/index.html.erb
<h1>Machines#index</h1>
<p>Find me in app/views/machines/index.html.erb</p>

app/views/machines/new.html.erb
<h1>Add New Machine</h1>
<%= form_for ([@project,@machine]) do |form| %>


  <p> Adding New Machine for <%= @project.name =%></p>
  <p>
    <%= form.label 'Name' %><br>
    <%= form.text_field :name %>
  </p>
  
  <p>
    <%= form.label :generator_capacity %><br>
    <%= form.text_field :generator_capacity %>
  </p>
 
  <p>
    <%= form.label 'generator_type' %><br>
    <%= form.text_field :generator_type %>
  </p>
  

  <p>
    <%= form.submit "Add Machine" %>
  </p>
<% end %>

app/views/machines/show.html.erb
<h1>Machine Details </h1> 
<h2><%= @project.name %> | <%= @machine.name %></h2>
<div class='project_info'>
<p>
  <strong>Project:</strong>
  <%= @project.name %>
</p>
 
<p>
  <strong>Location:</strong>
  <%= @project.location_text %>
</p>



<p>
  <strong>Machine:</strong>
  <%= @machine.name %>
</p>
<p>
  <strong>Machine Generator:</strong>
  <%= @machine.generator_type %>
</p>
<p>
  <strong>Machine Capacity:</strong>
  <%= @machine.generator_capacity %>
</p>
</div>

<%= form_for :search_form, url: get_ranged_generations_outages_project_machine_path(@project,@machine), method: :get do |form| %>
<table class='responstable'>
	<thead>
		<tr>
			<th colspan=3>Search for data</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<%= form.label :from_date, "Beginning date:" %>
				<%= form.text_field :from_date, :id=> 'from_date' %>
			</td>
			<td>
				<%= form.label :from_date, "End date:" %>
				<%= form.text_field :to_date, :id=> 'to_date' %>
			</td>
			<td><%= form.submit "Search" %></td>
		</tr>
	</tbody>
</table>
<% end %>
<div class='bottom_links'>
<ul>
<li><%= link_to 'Add Machine', new_project_machine_path(@project) %></li>
<li><%= link_to 'Go to Projects', projects_path %></li>
<ul>
</div>